# Generated by Django 4.0.5 on 2022-06-29 00:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='usersWatching',
            field=models.ManyToManyField(related_name='userWatch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='startingBid',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
        migrations.DeleteModel(
            name='watchList',
        ),
    ]
