# Generated by Django 4.0.5 on 2022-06-29 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings_userswatching_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='createdByUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userAuctionListings', to=settings.AUTH_USER_MODEL),
        ),
    ]
