# Generated by Django 4.0.5 on 2022-06-29 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlistings_createdbyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(blank=True, max_length=64, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='description',
            field=models.TextField(help_text='Describe Auction Listing', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='imageURL',
            field=models.URLField(blank=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='startingBid',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Start Bid'),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='title',
            field=models.CharField(help_text='Auction Title', max_length=64, verbose_name='Title'),
        ),
    ]
