# Generated by Django 4.0.5 on 2022-06-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlistings_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Title'),
        ),
    ]
