# Generated by Django 4.0.5 on 2022-06-29 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlistings_id_alter_bids_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='createdByUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAuctionListings', to=settings.AUTH_USER_MODEL),
        ),
    ]
