# Generated by Django 4.0.5 on 2022-06-29 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionlistings_createdbyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='startingBid',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.DecimalValidator(decimal_places=2, max_digits=19)], verbose_name='Start Bid'),
        ),
    ]
