# Generated by Django 4.0.5 on 2022-07-01 01:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auctionlistings_startingbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='startingBid',
            field=models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Starting Bid'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
