# Generated by Django 4.0.5 on 2022-07-02 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auctionlistings_listingmaxbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='listingMaxBid',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Current Bid'),
        ),
    ]
