# Generated by Django 4.0.5 on 2022-07-02 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auctionlistings_listingstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlistings',
            name='listingStatus',
        ),
    ]
