# Generated by Django 4.0.5 on 2022-07-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_remove_auctionlistings_listingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='listingStatus',
            field=models.BooleanField(default=True),
        ),
    ]
