# Generated by Django 4.0.5 on 2022-07-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_auctionlistings_listingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='listingStatus',
            field=models.BooleanField(default=True),
        ),
    ]
