# Generated by Django 4.0.5 on 2022-07-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auctionlistings_modifydate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlistings',
            name='modifyDate',
        ),
    ]
