# Generated by Django 4.0.5 on 2022-07-03 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_alter_auctionlistings_listingstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='auctionListing',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='userId',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='modifyDate',
        ),
    ]
