# Generated by Django 4.0.5 on 2022-07-03 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_alter_comments_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionlistings',
            options={'verbose_name_plural': 'Auction Listings'},
        ),
        migrations.AlterModelOptions(
            name='bids',
            options={'verbose_name_plural': 'Bids'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
