# Generated by Django 4.0.5 on 2022-07-03 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_alter_auctionlistings_options_alter_bids_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='listingMaxBid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Current Bid'),
        ),
    ]
